name: Facebook Live Stream

on:
  workflow_dispatch: # لتشغيل هذا العمل بشكل يدوي

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Start Facebook Live Stream
      run: |
        ffmpeg -re -i "http://stream.nubar.tv:1935/private/NUBARSport/halabja88.m3u8" \
        -c:v libx264 -preset veryfast -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -g 50 \
        -c:a aac -b:a 128k -ar 44100 -f flv \
        "rtmp://live-api-s.facebook.com:80/rtmp/${{ secrets.FB-122148065276313606-0-Aby2WCBkPzU0e4HC }}"
